language: python
python:
  - "3.6.8"
#command to install dependencies
install:
  - pip install face-recognition
  - pip install codecov
script:
  - pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
