language: python
python:
  - "3.6.8"
#command to install dependencies
cache: pip
install:
  - pip install face-recognition
  - pip install opencv-python
  - pip install coverage
  - pip install paho-mqtt
script:
  - pytest
after_success:
  - coverage run smartroom/src/test/test_FaceRecon.py
  - coverage report --fail-under=80
