language: python
python:
  - "3.6.8"
#command to install dependencies
install:
  - pip install face-recognition
  - pip install opencv-python
  - pip install coverage
script:
  - pytest
after_success:
  - coverage test_FaceRecon.py
