language: python
python:
  - "3.6.8"
#command to install dependencies
services:
  - docker
cache: pip
before_install:
  - docker pull matteobosco/smartroomserver:latest
  - docker run -d -p 1883:1883 matteobosco/smartroomserver /init.sh
install:
  - pip install face-recognition
  - pip install opencv-python
  - pip install coverage
  - pip install paho-mqtt
  - pip install pylint
script:
  - pytest
after_success:
  - coverage run smartroom/src/test/test_FaceRecon.py
  - coverage report -m
  - coverage run smartroom/src/test/test_AirModule.py
  - coverage report -m
  - coverage run smartroom/src/test/test_TempModule.py
  - coverage report -m
  - coverage run smartroom/src/test/test_LightModule.py
  - coverage report -m
  - coverage run server/src/test/test_Server.py
  - coverage report -m
  - pylint smartroom
  - pylint server
